services:
  backend:
    image: ghcr.io/thequorix/personal-website-backend:latest
    container_name: personal-website-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - db-data:/var/lib/personal-website/data
      - steam-icons:/app/data/steam-icons
    environment:
       - PORT=${PORT}
       - DATABASE_PATH=${DATABASE_PATH}
       - VISITOR_HASH_SALT=${VISITOR_HASH_SALT}
       - WEATHER_CITY=${WEATHER_CITY}
       - WEATHER_API_KEY=${WEATHER_API_KEY}
       - LAST_FM_USER=${LAST_FM_USER}
       - LAST_FM_API_KEY=${LAST_FM_API_KEY}
       - GITHUB_USERNAME=${GITHUB_USERNAME}
       - GITHUB_TOKEN=${GITHUB_TOKEN}
       - STEAM_ID=${STEAM_ID}
       - STEAM_API_KEY=${STEAM_API_KEY}
       - STEAM_GRID_DB_API_KEY=${STEAM_GRID_DB_API_KEY}
       - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
       - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  frontend:
    image: ghcr.io/thequorix/personal-website-frontend:latest
    container_name: personal-website-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NUXT_API_BASE=${NUXT_API_BASE}
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}

volumes:
  db-data:
  steam-icons: